GET http://localhost:5000/api/members

###
POST http://localhost:5000/api/members/
content-type: application/json

{
    "text": "sample 2"
}

###
PUT http://localhost:5000/api/members/630fe128445e0e2ed14d3527
content-type: application/json

{
  "text": "Updated"
}

###
PATCH http://localhost:5000/api/members/630fe128445e0e2ed14d3527
content-type: application/json

{
  "text": "Patched"
}

###
DELETE http://localhost:5000/api/members/630fe128445e0e2ed14d3527