GET http://localhost:5000/api/users

###
POST http://localhost:5000/api/users/
content-type: application/json

{
    "name": "Kimmo",
    "email": "kim@tkopeters.com",
    "password": "asdf"
}

###
POST http://localhost:5000/api/users/login
content-type: application/json

{
    "email": "travis@tkopeters.com",
    "password": "asdf"
}

###
GET http://localhost:5000/api/users/me


###
DELETE http://localhost:5000/api/users/630ff3e102b00d68f3598041